#!/bin/sh
#
# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

start() {
	local kernel_version=$(uname -r)

	if [ -d /sys/module/qca_nss_dscpstats ]; then
		echo "module qca-nss-dscpstats already loaded"
		return
	fi

	insmod /lib/modules/$kernel_version/kernel/drivers/qca-nss-dscpstats/qca-nss-dscpstats.ko num_clients=256
}

stop() {
	echo 1 > /sys/kernel/debug/qca-nss-dscpstats/conf/stop
	[ -d /sys/module/qca_nss_dscpstats ] && rmmod qca-nss-dscpstats
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    *)
	echo "Unsupported operation: available operations (start stop)"
esac
