#!/bin/sh
# Copyright (c) 2014, 2017-2019 The Linux Foundation. All rights reserved.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: ISC
#
get_front_end_mode() {
	front_end=$(syscfg get front_end)

	case $front_end in
	auto)
		echo '0'
		;;
	nss)
		echo '1'
		;;
	sfe)
		echo '2'
		;;
	ppe)
		echo '3'
		;;
	nss-sfe)
		echo '4'
		;;
	ppe-sfe)
		echo '5'
		;;
	sfe-ppe)
		echo '6'
		;;
	*)
		echo 'syscfg front_end option is invalid'
	esac
}

get_register_ip_post_routing() {
	ip_post_routing_hook=$(syscfg get ip_post_routing_hook)

	case $ip_post_routing_hook in
	enable)
		echo '1'
		;;
	disable)
		echo '0'
		;;
	*)
		echo 'Invalid option specified for ip post routing hook'
	esac
}

get_register_br_post_routing() {
	br_post_routing_hook=$(syscfg get br_post_routing_hook)

	case $br_post_routing_hook in
	enable)
		echo '1'
		;;
	disable)
		echo '0'
		;;
	*)
		echo 'Invalid option specified for br post routing hook'
	esac
}

get_sixth_tuple_mode() {
	sixth_tuple_mode=$(syscfg get sixth_tuple_mode)
	case $sixth_tuple_mode in
	vlan)
		echo '2'
		;;
	vsi)	echo '1'
		;;
	*)
		echo '0'
		;;
	esac
}

support_bridge() {
	#NSS support bridge acceleration
	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && return 0
	#SFE support bridge acceleration
	[ -d /sys/kernel/debug/ecm/ecm_sfe_ipv4 ] && return 0
	#PPE support bridge acceleration
	[ -d /sys/kernel/debug/ecm/ecm_ppe_ipv4 ] && return 0
}

load_sfe() {
	local kernel_version=$(uname -r)

	[ -e "/lib/modules/$kernel_version/kernel/drivers/qca-nss-sfe/qca-nss-sfe.ko" ] && {
		[ -d /sys/module/qca_nss_sfe ] && rmmod qca-nss-sfe
		if [ $(get_sixth_tuple_mode) == 0 ]; then
			modprobe qca_nss_sfe
		else
			modprobe qca_nss_sfe sixth_tuple_enable=1
		fi
	}

	if [ $(get_front_end_mode) == 6 ]; then
		echo 1 > /sys/sfe/flush_if_fls_breach
	fi
}

unload_flowmgr() {
	[ -d /sys/module/qca_nss_flowmgr ] && rmmod qca-nss-flowmgr
}

unload_sfe() {

	unload_flowmgr
	[ -d /sys/module/qca_nss_sfe ] && rmmod qca-nss-sfe
}

ecm_dependency() {
	[ -e /lib/modules/$(uname -r)/kernel/drivers/qca-emesh-sp/emesh-sp.ko ] && modprobe emesh-sp
	[ -e /lib/modules/$(uname -r)/kernel/net/netfilter/nf_conntrack.ko ] && modprobe nf_conntrack
	[ -e /lib/modules/$(uname -r)/kernel/drivers/qca-nss-ppe/qca-nss-ppe.ko ] && modprobe qca-nss-ppe
	[ -e /lib/modules/$(uname -r)/kernel/drivers/qca-ovsmgr/qca-ovsmgr.ko ] && modprobe qca-ovsmgr
	[ -e /lib/modules/$(uname -r)/kernel/drivers/net/bonding/bonding.ko ] && modprobe bonding
	[ -e /lib/modules/$(uname -r)/kernel/net/l2tp/l2tp_ppp.ko ] && modprobe l2tp_ppp
	[ -e /lib/modules/$(uname -r)/kernel/drivers/qca-nss-ppe-vxlanmgr/qca-nss-ppe-vxlanmgr.ko ] && modprobe qca-nss-ppe-vxlanmgr
	[ -e /proc/sys/ppe/ppe_drv/ppe_drv_sixth_tuple_en ] && {
			echo "$(get_sixth_tuple_mode)" > /proc/sys/ppe/ppe_drv/ppe_drv_sixth_tuple_en
	}
}

load_ecm() {

	[ -d /sys/module/ecm ] || {
		ecm_dependency
		modprobe ecm front_end_selection=$(get_front_end_mode) register_ip_post_routing=$(get_register_ip_post_routing) register_br_post_routing=$(get_register_br_post_routing) ecm_front_end_ipv4_stopped=1 ecm_front_end_ipv6_stopped=1

		if [ $(get_front_end_mode) == 4 ]; then
			modprobe ecm_ae_select
		fi
	}

	# Set conntrack event mode to 1 for 6.1 kernel to get the conntrack events from ECM
	local kernel_major=`uname -r |cut -d. -f1`
	if [ $kernel_major == 6 ]; then
		echo 1 > /proc/sys/net/netfilter/nf_conntrack_events
	fi

	local kernel_version=$(uname -r)

	[ -e "/lib/modules/$kernel_version/kernel/drivers/qca-nss-wifi-plugins/qca-wifi-nss-plugins.ko" ] && {
		[ -d /sys/module/qca_wifi_nss_plugins ] || [ -d /sys/module/umac ] ||
		[ -f /lib/modules/$kernel_version/ath.ko ] && modprobe qca_wifi_nss_plugins
	}

	echo 0 > /sys/kernel/debug/ecm/front_end_ipv4_stop
	echo 0 > /sys/kernel/debug/ecm/front_end_ipv6_stop

	support_bridge && {
		sysctl -w net.bridge.bridge-nf-call-ip6tables=1
		sysctl -w net.bridge.bridge-nf-call-iptables=1
	}
}

unload_ecm() {
	sysctl -w net.bridge.bridge-nf-call-ip6tables=0
	sysctl -w net.bridge.bridge-nf-call-iptables=0

	# Change it back to 6.1 linux's default setting
	local kernel_major=`uname -r |cut -d. -f1`
	if [ $kernel_major == 6 ]; then
		echo 2 > /proc/sys/net/netfilter/nf_conntrack_events
	fi

	if [ -d /sys/module/ecm ]; then
		#
		# Stop ECM frontends
		#
		echo 1 > /proc/sys/net/ecm/front_end_ipv4_stop
		echo 1 > /proc/sys/net/ecm/front_end_ipv6_stop

		#
		# Defunct the connections
		#
	        echo 1 > /proc/sys/net/ecm/ecm_db/defunct_all
		sleep 5;

		#
		# unload qca-wifi-nss-plugins
		#
		if [ -d /sys/module/qca_wifi_nss_plugins ]; then
			rmmod qca-wifi-nss-plugins
		fi

		if [ -d /sys/module/ecm_ae_select ]; then
			rmmod ecm_ae_select
		fi

		rmmod ecm
		sleep 1
	fi
}

start() {

	load_sfe
	load_ecm

	# If the acceleration engine is NSS, enable wifi redirect.
	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=1

	support_bridge && {
		# Delete original configuration before appending new
		[ -f /etc/sysctl.d/qca-nss-ecm.conf ] && {
			sed '/net.bridge.bridge-nf-call-ip6tables/d' -i /etc/sysctl.d/qca-nss-ecm.conf
			sed '/net.bridge.bridge-nf-call-iptables/d' -i /etc/sysctl.d/qca-nss-ecm.conf
		}
		echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.d/qca-nss-ecm.conf
		echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.d/qca-nss-ecm.conf
	}

	if [ -d /sys/module/qca_ovsmgr ]; then
		modprobe ecm_ovs
	fi

	# Enable SAWF and EMESH classifier by default for Out-of box prioritization
	echo 3 > /proc/sys/net/ecm/ecm_classifier_emesh/enabled
	echo 3 > /proc/sys/net/ecm/ecm_classifier_emesh/sawf_enabled

	# If UDP classifier is present, start it.
	[ -f /usr/bin/udp-clf ] && systemctl start udp-clf
}

stop() {
	# If ECM is already not loaded, just return.
	if [ ! -d /sys/module/ecm ]; then
		return
	fi

	# If UDP classifier is present, stop it.
	# Update udp-clf init script, RDK uses systemctl
	[ -f /usr/bin/udp-clf ] && systemctl stop udp-clf

	# If the acceleration engine is NSS, disable wifi redirect.
	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=0

	[ -f /etc/sysctl.d/qca-nss-ecm.conf ] && {
		sed '/net.bridge.bridge-nf-call-ip6tables=1/d' -i /etc/sysctl.d/qca-nss-ecm.conf
		sed '/net.bridge.bridge-nf-call-iptables=1/d' -i /etc/sysctl.d/qca-nss-ecm.conf
	}

	if [ -d /sys/module/ecm_ovs ]; then
		rmmod ecm_ovs
	fi

	unload_ecm
	unload_sfe
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    *)
	echo "Unsupported operation: available operations (start stop restart)"
esac
